LetMasterWebApp/Pages/Reports/AccountStatement.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LetMasterWebApp.Pages.Reports;
[Authorize(Roles = "Manager")]
public class AccountStatementModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public ReportSearchModel searchModel { get; set; } = new ReportSearchModel();
    public AccountStatement accountStatement { get; set; }= new AccountStatement();
    public List<SelectListItem>? properties { get; set; }
    public List<SelectListItem>? accounts { get; set; }
    //service injection
    private readonly UserManager<User> _userManager;
    private readonly IReportingServices _reportingService;
    public AccountStatementModel(UserManager<User> userManager, IReportingServices reportingService)
    {
        _userManager = userManager;
        _reportingService = reportingService;
    }

    public async Task OnGetAsync()
    {
        searchModel.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
    }
    public async Task OnPostAsync()
    {
        searchModel.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        accountStatement = await _reportingService.GetTenantAccountStatementAsync(searchModel);
    }
    public async Task<IActionResult> OnGetTenantAccountsAsync(int propertyId)
    {
        try
        {
            var tenantAccounts = await _reportingService.GetTenantAccountsSelectList(propertyId);
            return new JsonResult(tenantAccounts);
        }
        catch
        {
            return StatusCode(500, "Internal server error");
        }
    }
    public async Task<IActionResult> OnPostExportAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        accountStatement = await _reportingService.GetTenantAccountStatementAsync(searchModel);
        return DataExportHelper.ExportToExcel(accountStatement.AccountTransactions!, $"AccountStatement-{accountStatement.Tenant}-{accountStatement.UnitNo}.xlsx");
    }
}

LetMasterWebApp/Pages/Reports/ExpenseReport.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LetMasterWebApp.Pages.Reports;
[Authorize(Roles = "Manager,Admin")]
public class ExpenseReportModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public ReportSearchModel? searchModel { get; set; } = new ReportSearchModel();
    public List<SelectListItem>? properties { get; set; }
    public PropertyExpense? expenses { get; set; }// = new PropertyExpense();
    //service injection
    private readonly UserManager<User> _userManager;
    private readonly IReportingServices _reportingService;
    public ExpenseReportModel(UserManager<User> userManager, IReportingServices reportingService)
    {
        _userManager = userManager;
        _reportingService = reportingService;
    }

    public async Task OnGetAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
    }
    public async Task OnPostAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        expenses = await _reportingService.GetPropertyExpensesAsync(searchModel);
    }
    public async Task<IActionResult> OnPostExportAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        expenses = await _reportingService.GetPropertyExpensesAsync(searchModel);
        return DataExportHelper.ExportToExcel(expenses.Expenses, $"ExpenseReport-{expenses.PropertyName}.xlsx");
    }
}

LetMasterWebApp/Pages/Reports/Notifications.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LetMasterWebApp.Pages.Reports;
[Authorize(Roles = "Admin")]
public class NotificationsModel : PageModel
{
    public PaginatedList<UserMessage>? Messages { get; set; }
    [BindProperty(SupportsGet = true)]
    public ReportSearchModel? searchModel { get; set; } = new ReportSearchModel();
    private readonly UserManager<User> _userManager;
    private readonly IReportingServices _reportingService;
    public NotificationsModel(UserManager<User> userManager, IReportingServices reportingService)
    {
        _userManager = userManager;
        _reportingService = reportingService;
    }

    public void OnGet()
    {
    }
    public async Task OnPostAsync()
    {
        Messages = await _reportingService.GetNotificationsAsync(searchModel);
    }
}

LetMasterWebApp/Pages/Reports/OccupancyReport.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LetMasterWebApp.Pages.Reports;
public class OccupancyReportModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public ReportSearchModel? searchModel { get; set; } = new ReportSearchModel();
    public List<SelectListItem>? properties { get; set; }
    public PropertyOccupancyReport? occupancyReport { get; set; }// = new PropertyOccupancyReport();
    //service injection
    private readonly UserManager<User> _userManager;
    private readonly IReportingServices _reportingService;
    public OccupancyReportModel(UserManager<User> userManager, IReportingServices reportingService)
    {
        _userManager = userManager;
        _reportingService = reportingService;
    }
    public async Task OnGetAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
    }
    public async Task OnPostAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        occupancyReport = await _reportingService.GetOccupancyReportAsync(searchModel);
    }
    public async Task<IActionResult> OnPostExportAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        occupancyReport = await _reportingService.GetOccupancyReportAsync(searchModel);
        return DataExportHelper.ExportToExcel(occupancyReport.UnitDetails!, $"OccupancyReport-{occupancyReport.PropertyName}.xlsx");
    }
}

LetMasterWebApp/Pages/Reports/PropertyTransactionReport.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LetMasterWebApp.Pages.Reports;
public class PropertyTransactionReportModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public ReportSearchModel? searchModel { get; set; } = new ReportSearchModel();
    public List<SelectListItem>? properties { get; set; }
    public PropertyRentTransaction? rentTransaction { get; set; }
    private readonly UserManager<User> _userManager;
    private readonly IReportingServices _reportingService;
    public PropertyTransactionReportModel(UserManager<User> userManager, IReportingServices reportingService)
    {
        _userManager = userManager;
        _reportingService = reportingService;
    }
    public async Task OnGetAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
    }
    public async Task OnPostAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        rentTransaction = await _reportingService.GetRentTransactionAsync(searchModel);
    }
    public async Task<IActionResult> OnPostExportAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        properties = await _reportingService.GetPropertySelectList(searchModel.UserId!);
        rentTransaction = await _reportingService.GetRentTransactionAsync(searchModel);
        return DataExportHelper.ExportToExcel(rentTransaction.TransactionEntries!, $"RentTransactionReport-{rentTransaction.PropertyName}.xlsx");
    }
}

LetMasterWebApp/Pages/Reports/TenantAccountStatement.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LetMasterWebApp.Pages.Reports;

public class TenantAccountStatementModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public ReportSearchModel searchModel { get; set; } = new ReportSearchModel();
    public AccountStatement accountStatement { get; set; } = new AccountStatement();
    public List<SelectListItem>? accounts { get; set; }
    //service injection
    private readonly UserManager<User> _userManager;
    private readonly IReportingServices _reportingService;
    public TenantAccountStatementModel(UserManager<User> userManager, IReportingServices reportingService)
    {
        _userManager = userManager;
        _reportingService = reportingService;
    }

    public async Task OnGetAsync(int id)
    {
        searchModel.UserId = _userManager.GetUserId(User);
        searchModel.TenantAccountId = id;
        accounts = await _reportingService.GetAccountsSelectList(searchModel.UserId!);
    }
    public async Task OnPostAsync()
    {
        searchModel.UserId = _userManager.GetUserId(User);
        accounts = await _reportingService.GetAccountsSelectList(searchModel.UserId!);
        accountStatement = await _reportingService.GetAccountTransactionsAsync(searchModel);
    }
    public async Task<IActionResult> OnPostExportAsync()
    {
        searchModel!.UserId = _userManager.GetUserId(User);
        accounts = await _reportingService.GetAccountsSelectList(searchModel.UserId!);
        accountStatement = await _reportingService.GetAccountTransactionsAsync(searchModel);
        return DataExportHelper.ExportToExcel(accountStatement.AccountTransactions!, $"AccountStatement-{accountStatement.PropertyName}-{accountStatement.UnitNo}.xlsx");
    }
}

LetMasterWebApp/Pages/Reports/AccountStatement.cshtml
@page "/AccountStatement"
@model LetMasterWebApp.Pages.Reports.AccountStatementModel
@{
    ViewData["Title"] = "Account Statement";
}
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/ExpenseReport">Expense Report</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/OccupancyReport">Occupancy Report</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/PropertyTransactionReport">Property Rent Transaction Report</a>
<h2>Account Statement</h2>
<div class="mb-3">
    <form method="post">
        <div class="d-flex flex-wrap">
            <div class="form-group mr-3">
                <label for="PropertyId" class="mr-2">Property</label>
                <select id="PropertyId" name="searchModel.PropertyId" class="form-control mr-2" required>
                    <option value="">Select Property</option>
                    @foreach (var property in Model.properties!)
                    {
                        <option value="@property.Value">@property.Text</option>
                    }
                </select>
            </div>
            <div class="form-group mr-3">
                <label for="TenantAccountId" class="mr-2">Tenant Account</label>
                <select id="TenantAccountId" name="searchModel.TenantAccountId" class="form-control mr-2" required>
                    <option value="">Select Account</option>
                </select>
            </div>
            <div class="form-group mr-3">
                <label for="DateFrom" class="mr-2">Date From</label>
                <input type="date" id="DateFrom" name="searchModel.DateFrom" class="form-control mr-2" value="@Model.searchModel.DateFrom.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group mr-3">
                <label for="DateTo" class="mr-2">Date To</label>
                <input type="date" id="DateTo" name="searchModel.DateTo" class="form-control mr-2" value="@Model.searchModel.DateTo.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group align-self-end">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>
@if (Model.accountStatement.AccountTransactions != null && Model.accountStatement.AccountTransactions.Count > 0)
{
    <h3 class="mt-3">Account Transactions: @Model.accountStatement.Tenant</h3>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <p class="card-text"><b>Property Name (Unit No.)</b>: @Model.accountStatement.PropertyName (@Model.accountStatement.UnitNo)</p>
                <p class="card-text"><b>Location</b>: @Model.accountStatement.PropertyAddress</p>
                <p class="card-text"><b>Current Agreed Rate.</b>: @Model.accountStatement.AgreedRate!.Value.ToString("N2")</p>
                <p class="card-text"><b>Current Balance</b>: @Model.accountStatement.CurrentBalance!.Value.ToString("N2")</p>
            </div>
            <div class="col-sm-6">
                <p class="card-text"><b>Tenant</b>: @Model.accountStatement.Tenant</p>
                <p class="card-text"><b>Email</b>: @Model.accountStatement.TenantEmail</p>
                <p class="card-text"><b>Phone</b>: @Model.accountStatement.TenantContact</p>
            </div>
        </div>
    </div>

    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <th>Transaction Type</th>
                <th>Description</th>
                <th>Reference No.</th>
                <th>Mode</th>
                <th>Amount</th>
                <th>Transaction Date</th>
                <th>Date Posted</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var transaction in Model.accountStatement.AccountTransactions)
            {
                <tr>
                    <td>
                        @if (transaction.TransactionType == "D")
                        {
                            <text>DEBIT</text>
                        }
                        else if (transaction.TransactionType == "C")
                        {
                            <text>CREDIT</text>
                        }
                    </td>
                    <td>@transaction.TransactionDesc</td>
                    <td>@transaction.TransactionRef</td>
                    <td>@transaction.TransactionMode</td>
                    <td>@transaction.Amount!.Value.ToString("C")</td>
                    <td>@transaction.TransactionDate.ToString("yyyy-MM-dd")</td>
                    <td>@transaction.TransactionCreationDate?.ToString("yyyy-MM-dd")</td>
                </tr>
            }
        </tbody>
    </table>
    <form method="post" asp-page-handler="ExportToExcel">
        <input type="hidden" name="searchModel.TenantAccountId" value="@Model.searchModel?.TenantAccountId" />
        <input type="hidden" name="searchModel.TransactionType" value="@Model.searchModel?.TransactionType" />
        <input type="hidden" name="searchModel.DateFrom" value="@Model.searchModel?.DateFrom.ToString("yyyy-MM-dd")" />
        <input type="hidden" name="searchModel.DateTo" value="@Model.searchModel?.DateTo.ToString("yyyy-MM-dd")" />
        <button type="submit" class="btn btn-success mt-2" value="Export" asp-page-handler="Export">Export Data</button>
    </form>
}
else
{
    <p>No transactions found for the selected criteria.</p>
}
@section Scripts {
    <script>
        $(document).ready(function () {
            // Cascading dropdowns for property and tenant account
            $('#PropertyId').change(function () {
                var propertyId = $(this).val();
                if (propertyId) {
                    $.ajax({
                        url: '/AccountStatement?handler=TenantAccounts',
                        type: 'GET',
                        data: { propertyId: propertyId },
                        success: function (data) {
                            var accDropdown = $('#TenantAccountId');
                            accDropdown.empty();
                            accDropdown.append('<option value="">Select Account</option>');
                            $.each(data, function (index, item) {
                                accDropdown.append('<option value="' + item.value + '">' + item.text + '</option>');
                            });
                        },
                        error: function (xhr, status, error) {
                            console.error("Error: " + error);
                        }
                    });
                } else {
                    $('#TenantAccountId').empty().append('<option value="">Select Account</option>');
                }
            });
        });
    </script>
}

LetMasterWebApp/Pages/Reports/ExpenseReport.cshtml
@page "/Expenses"
@model LetMasterWebApp.Pages.Reports.ExpenseReportModel
@{
    ViewData["Title"] = "Property Expense Report";
}
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/AccountStatement">Tenant Account Statement</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/OccupancyReport">Occupancy Report</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/PropertyTransactionReport">Property Rent Transaction Report</a>
<h2>Expense Report</h2>
<div class="mb-3">
    <form method="post">
        <div class="d-flex flex-wrap">
            <div class="form-group mr-3">
                <label for="PropertyId" class="mr-2">Property</label>
                <select id="PropertyId" name="searchModel.PropertyId" class="form-control mr-2" required>
                    <option value="">Select Property</option>
                    @foreach (var property in Model.properties!)
                    {
                        if (property.Value == Model.searchModel?.PropertyId?.ToString())
                        {
                            <option value="@property.Value" selected>@property.Text</option>
                        }
                        else
                        {
                            <option value="@property.Value">@property.Text</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group mr-3">
                <label for="DateFrom" class="mr-2">Date From</label>
                <input type="date" id="DateFrom" name="searchModel.DateFrom" class="form-control mr-2" value="@Model.searchModel!.DateFrom.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group mr-3">
                <label for="DateTo" class="mr-2">Date To</label>
                <input type="date" id="DateTo" name="searchModel.DateTo" class="form-control mr-2" value="@Model.searchModel.DateTo.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group align-self-end">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>
@if (Model.expenses != null && Model.expenses.Expenses.Count > 0)
{
    <h3 class="mt-3">Expenses: @Model.expenses.PropertyName</h3>
    <p><b>Location</b>: @Model.expenses.PropertyAddress</p>
    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <th>Unit No</th>
                <th>Expense Description</th>
                <th>Expense Type</th>
                <th>Amount</th>
                <th>Transaction Date</th>
                <th>Date Posted</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var expense in Model.expenses.Expenses)
            {
                <tr>
                    <td>@expense.UnitNo</td>
                    <td>@expense.ExpenseDesc</td>
                    <td>@expense.ExpenseType</td>
                    <td>@expense.Amount!.Value.ToString("N2")</td>
                    <td>@expense.TransactionDate.ToString("yyyy-MM-dd")</td>
                    <td>@expense.TransactionCreationDate?.ToString("yyyy-MM-dd")</td>
                </tr>
            }
        </tbody>
    </table>
    <form method="post" asp-page-handler="ExportToExcel">
        <input type="hidden" name="searchModel.PropertyId" value="@Model.searchModel?.PropertyId" />
        <input type="hidden" name="searchModel.DateFrom" value="@Model.searchModel?.DateFrom.ToString("yyyy-MM-dd")" />
        <input type="hidden" name="searchModel.DateTo" value="@Model.searchModel?.DateTo.ToString("yyyy-MM-dd")" />
        <button type="submit" class="btn btn-success mt-2" value="Export" asp-page-handler="Export">Export Data</button>
    </form>
}
else
{
    <p>No expenses found for the selected criteria.</p>
}

LetMasterWebApp/Pages/Reports/OccupancyReport.cshtml
@page "/Occupancy"
@model LetMasterWebApp.Pages.Reports.OccupancyReportModel
@{
    ViewData["Title"] = "Property Occupancy Report";
}
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/ExpenseReport">Expense Report</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/AccountStatement">Tenant Account Statement</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/PropertyTransactionReport">Property Rent Transaction Report</a>
<h2>Property Occupancy Report</h2>
<div class="mb-3">
    <form method="post">
        <div class="d-flex flex-wrap">
            <div class="form-group mr-3">
                <label for="PropertyId" class="mr-2">Property</label>
                <select id="PropertyId" name="searchModel.PropertyId" class="form-control mr-2" required>
                    <option value="">Select Property</option>
                    @foreach (var property in Model.properties!)
                    {
                        if (property.Value == Model.searchModel?.PropertyId?.ToString())
                        {
                            <option value="@property.Value" selected>@property.Text</option>
                        }
                        else
                        {
                            <option value="@property.Value">@property.Text</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group align-self-end">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>
@if (Model.occupancyReport != null&&Model.occupancyReport.UnitDetails != null && Model.occupancyReport.UnitDetails.Count > 0)
{
    <h3 class="mt-3">Occupancy Report: @Model.occupancyReport.PropertyName</h3>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <p class="card-text"><b>Property Location</b>: @Model.occupancyReport.PropertyAddress</p>
                <p class="card-text"><b>Property Type</b>: @Model.occupancyReport.PropertyType</p>
                <p class="card-text"><b>Description</b>: @Model.occupancyReport.PropertyDesc</p>
            </div>
            <div class="col-sm-6">
                <p class="card-text"><b>Total Units</b>: @Model.occupancyReport.TotalUnits</p>
                <p class="card-text"><b>Occupied Units</b>: @Model.occupancyReport.OccupiedUnits</p>
            </div>
        </div>
    </div>
    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <th>Unit No.</th>
                <th>Unit Type</th>
                <th>Standard Rate</th>
                <th>Is Occupied</th>
                <th>Current Tenant</th>
                <th>Tenancy Start Date</th>
                <th>Tenant Contact</th>
                <th>Tenant Email</th>
                <th>Agreed Rate</th>
                <th>Current Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var unit in Model.occupancyReport.UnitDetails)
            {
                <tr>
                    <td>@unit.UnitNo</td>
                    <td>@unit.UnitType</td>
                    <td>@unit.StandardRate!.Value.ToString("N2")</td>
                    <td>@unit.IsOccupied</td>
                    <td>@unit.TenantName</td>
                    <td>@unit.StartDate?.ToString("yyyy-MM-dd")</td>
                    <td>@unit.TenantContact</td>
                    <td>@unit.TenantEmail</td>
                    <td>@unit.AgreedRate?.ToString("C")</td>
                    <td>@unit.CurrentBalance?.ToString("N2")</td>
                </tr>
            }
        </tbody>
    </table>
    <form method="post" asp-page-handler="ExportToExcel">
        <input type="hidden" name="searchModel.PropertyId" value="@Model.searchModel?.PropertyId" />
        <button type="submit" class="btn btn-success mt-2" value="Export" asp-page-handler="Export">Export Data</button>
    </form>
}
else
{
    <p>No data found for the selected criteria.</p>
}

LetMasterWebApp/Pages/Reports/PropertyTransactionReport.cshtml
@page "/PropertyTransaction"
@model LetMasterWebApp.Pages.Reports.PropertyTransactionReportModel
@{
    ViewData["Title"] = "Property Transaction Report";
}
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/ExpenseReport">Expense Report</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/AccountStatement">Tenant Account Statement</a>
<a class="btn btn-sm btn-warning manage-btn" asp-page="/reports/OccupancyReport">Occupancy Report</a>
<h2>Property Transaction Report</h2>
<div class="mb-3">
    <form method="post">
        <div class="d-flex flex-wrap">
            <div class="form-group mr-3">
                <label for="PropertyId" class="mr-2">Property</label>
                <select id="PropertyId" name="searchModel.PropertyId" class="form-control mr-2" required>
                    <option value="">Select Property</option>
                    @foreach (var property in Model.properties!)
                    {
                        if (property.Value == Model.searchModel?.PropertyId?.ToString())
                        {
                            <option value="@property.Value" selected>@property.Text</option>
                        }
                        else
                        {
                            <option value="@property.Value">@property.Text</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group mr-3">
                <label for="DateFrom" class="mr-2">Date From</label>
                <input type="date" id="DateFrom" name="searchModel.DateFrom" class="form-control mr-2" value="@Model.searchModel!.DateFrom.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group mr-3">
                <label for="DateTo" class="mr-2">Date To</label>
                <input type="date" id="DateTo" name="searchModel.DateTo" class="form-control mr-2" value="@Model.searchModel.DateTo.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group align-self-end">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>
@if (Model.rentTransaction != null && Model.rentTransaction.TransactionEntries!=null && Model.rentTransaction.TransactionEntries.Count > 0)
{
    <h3 class="mt-3">Rent Transactions: @Model.rentTransaction.PropertyName</h3>
    <p><b>Location</b>: @Model.rentTransaction.PropertyAddress</p>
    <table class="table table-striped mt-3">
        <thead>
            <tr>
                <th>Unit No.</th>
                <th>Tenant</th>
                <th>Transaction Type</th>
                <th>Description</th>
                <th>Reference No.</th>
                <th>Mode</th>
                <th>Amount</th>
                <th>Transaction Date</th>
                <th>Date Posted</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var transaction in Model.rentTransaction.TransactionEntries)
            {
                <tr>
                    <td>@transaction.UnitNo</td>
                    <td>@transaction.TenantName</td>
                    <td>
                        @if (transaction.TransactionType == "D")
                        {
                            <text>DEBIT</text>
                        }
                        else if (transaction.TransactionType == "C")
                        {
                            <text>CREDIT</text>
                        }
                    </td>
                    <td>@transaction.TransactionDesc</td>
                    <td>@transaction.TransactionRef</td>
                    <td>@transaction.TransactionMode</td>
                    <td>@transaction.Amount!.Value.ToString("N2")</td>
                    <td>@transaction.TransactionDate?.ToString("yyyy-MM-dd")</td>
                    <td>@transaction.TransactionCreationDate?.ToString("yyyy-MM-dd")</td>
                </tr>
            }
        </tbody>
    </table>
    <form method="post" asp-page-handler="ExportToExcel">
        <input type="hidden" name="searchModel.PropertyId" value="@Model.searchModel?.PropertyId" />
        <input type="hidden" name="searchModel.DateFrom" value="@Model.searchModel?.DateFrom.ToString("yyyy-MM-dd")" />
        <input type="hidden" name="searchModel.DateTo" value="@Model.searchModel?.DateTo.ToString("yyyy-MM-dd")" />
        <button type="submit" class="btn btn-success mt-2" value="Export" asp-page-handler="Export">Export Data</button>
    </form>
}
else
{
    <p>No expenses found for the selected criteria.</p>
}