LetMasterWebApp/Pages/TenantMgt/ListTenantAccounts.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LetMasterWebApp.Pages.TenantMgt;
[Authorize]
public class ListTenantAccountsModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public TenantUnitSearchModel searchModel { get; set; } = new TenantUnitSearchModel();
    public PaginatedList<TenantUnitViewModel>? tenantAccountList { get; set; }
    //Service injection
    private readonly ILogger<ListTenantAccountsModel> _logger;
    private readonly ITenantServices _tenantServices;
    private readonly UserManager<User> _userManager;
    public ListTenantAccountsModel(ILogger<ListTenantAccountsModel> logger, ITenantServices tenantServices, UserManager<User> userManager)
    {
        _logger = logger;
        _tenantServices = tenantServices;
        _userManager = userManager;
    }

    public async Task OnGetAsync(int pageIndex = 1)
    {
        try
        {
            searchModel.TenantUserId = _userManager.GetUserId(User);
            searchModel.Page = pageIndex;
            tenantAccountList = await _tenantServices.ListTenantAccountsAsync(searchModel);
        }
        catch (Exception ex)
        {
            _logger.LogError($"Error OnGetAsync: {ex}");
        }
    }
}

LetMasterWebApp/Pages/TenantMgt/ListTenants.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LetMasterWebApp.Pages.TenantMgt;
[Authorize]
public class ListTenantsModel : PageModel
{
    [BindProperty(SupportsGet = true)]
    public TenantUnitSearchModel searchModel { get; set; } = new TenantUnitSearchModel();
    public PaginatedList<TenantUnitViewModel>? tenantList { get; set; }
    public List<SelectListItem>? properties { get; set; }
    public List<SelectListItem>? tenants { get; set; }
    [BindProperty]
    public TenantUnitCreateModel createModel { get; set; }=new TenantUnitCreateModel();
    private readonly ILogger<ListTenantsModel> _logger;
    private readonly ITenantServices _tenantServices;
    private readonly UserManager<User> _userManager;
    public ListTenantsModel(ILogger<ListTenantsModel> logger, ITenantServices tenantServices, UserManager<User> userManager)
    {
        _logger = logger;
        _tenantServices = tenantServices;
        _userManager = userManager;
    }

    public async Task OnGetAsync(int pageIndex = 1)
    {
        try
        {
            searchModel.PropertyManagerId = _userManager.GetUserId(User);
            searchModel.Page = pageIndex;
            tenantList = await _tenantServices.ListTenantAccountsAsync(searchModel);
            properties=await _tenantServices.GetPropertySelectList(searchModel.PropertyManagerId!);
            tenants=await _tenantServices.GetTenantsAsync(searchModel.PropertyManagerId!);
            createModel.CreatedBy=searchModel.PropertyManagerId;
        }
        catch (Exception ex)
        {
            _logger.LogError($"Error OnGetAsync: {ex}");
        }
    }
    public async Task<IActionResult> OnGetVacantUnitsAsync(int propertyId)
    {
        try
        {
            var vacantUnits = await _tenantServices.GetVacantUnitsAsync(propertyId);
            return new JsonResult(vacantUnits);
        }
        catch (Exception ex)
        {
            _logger.LogError($"Error OnGetVacantUnitsAsync: {ex}");
            return StatusCode(500, "Internal server error");
        }
    }
    public async Task<IActionResult> OnPostCreateUnitAccAsync()
    {
        try
        {
            var state = ModelState.IsValid;
            createModel.CreatedBy = _userManager.GetUserId(User);
            var success = await _tenantServices.CreateTenantUnitAccountAsync(createModel);
            if (success)
            {
                TempData["AlertMessage"] = "Tenant Account Creation Successful";
                return RedirectToPage("/TenantMgt/ListTenants");
            }
                
            else
            {
                TempData["ErrorMessage"] = "Tenant Account Creation Failed";
                ModelState.AddModelError(string.Empty, "Property creation failed.");
            }
                
        }
        catch (BadHttpRequestException ex)
        {
            TempData["ErrorMessage"] = "Tenant Account Creation Failed";
            _logger.LogError($"Error OnPostCreateUnitAccAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = "Tenant Account Creation Failed";
            _logger.LogError($"Error OnPostCreateUnitAccAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        return Page();
    }
}

LetMasterWebApp/Pages/TenantMgt/ManageTenantAccount.cshtml.cs
using LetMasterWebApp.Core;
using LetMasterWebApp.Models;
using LetMasterWebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LetMasterWebApp.Pages.TenantMgt;
[Authorize]
public class ManageTenantAccountModel : PageModel
{
    public PaginatedList<TenantUnitTransaction>? transactionList { get; set; }
    [BindProperty(SupportsGet = true)]
    public TenantUnitTransactionSearchModel? transactionSearch { get; set; } = new TenantUnitTransactionSearchModel();
    [BindProperty]
    public TenantUnitTransactionCreateModel? transactionCreate { get; set; } = new TenantUnitTransactionCreateModel { Amount = 0, Description = string.Empty, TenantUnitId = 0, TransactionDate = DateTime.Now, TransactionType = "D" };
    [BindProperty]
    public MobileMoneyCreateModel? mobileMoneyCreate { get; set; } = new MobileMoneyCreateModel { Amount = 0, DebitNumber = "", TenantUnitId = 0 };
    [BindProperty]
    public TenantUnitUpdateModel? accountUpdate { get; set; } = new TenantUnitUpdateModel { Id = 0 };
    public TenantUnitViewDetail? accountDetails { get; set; }

    private readonly ILogger<ManageTenantAccountModel> _logger;
    private readonly ITenantServices _tenantServices;
    private readonly UserManager<User> _userManager;
    private readonly IPaymentService _paymentService;
    private readonly IConfiguration _configuration;
    public ManageTenantAccountModel(ILogger<ManageTenantAccountModel> logger, ITenantServices tenantServices, UserManager<User> userManager, IPaymentService paymentService, IConfiguration configuration)
    {
        _logger = logger;
        _tenantServices = tenantServices;
        _userManager = userManager;
        _paymentService = paymentService;
        _configuration = configuration;
    }
    public async Task<IActionResult> OnGetAsync(int id, int pageIndex = 1)
    {
        accountDetails = await _tenantServices.GetTenantAccountDetailsAsync(id);
        transactionSearch!.TenantUnitId = id;
        transactionSearch.Page = pageIndex;
        transactionCreate!.CreatedBy = _userManager.GetUserId(User);
        transactionCreate!.TenantUnitId = id;
        accountUpdate!.Id = id;
        accountUpdate.AgreedRate = accountDetails.AgreedRate;
        transactionList = await _tenantServices.GetTransactionsAsync(transactionSearch);
        mobileMoneyCreate!.TenantUnitId = id;
        return Page();
    }
    public async Task<IActionResult> OnPostUpdateTenantAccountAsync()
    {
        try
        {
            var state = ModelState.IsValid;
            accountUpdate!.UpdatedBy = _userManager.GetUserId(User);
            var success = await _tenantServices.UpdateTenantAccountAsync(accountUpdate);
            if (success)
            {
                TempData["AlertMessage"] = "Account Update Successful";
                return RedirectToPage();
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Account Update Failed.");
                TempData["ErrorMessage"] = "Account Update Failed";
            }
        }
        catch (BadHttpRequestException ex)
        {
            TempData["ErrorMessage"] = "Account Update Failed";
            _logger.LogError($"Error OnPostUpdateTenantAccountAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = "Account Update Failed";
            _logger.LogError($"Error OnPostUpdateTenantAccountAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        return Page();
    }
    public async Task<IActionResult> OnPostPostTransactionAsync()
    {
        try
        {
            var state = ModelState.IsValid;
            transactionCreate!.CreatedBy = _userManager.GetUserId(User);
            var success = await _tenantServices.PostTransactionAsync(transactionCreate);
            if (success)
            {
                TempData["AlertMessage"] = "Post Transaction Successful";
                return RedirectToPage();
            }
            else
            {
                TempData["ErrorMessage"] = "Post Transaction Failed";
                ModelState.AddModelError(string.Empty, "Post Transaction Failed.");
            }
        }
        catch (BadHttpRequestException ex)
        {
            TempData["ErrorMessage"] = "Post Transaction Failed";
            _logger.LogError($"Error OnPostPostTransactionAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = "Post Transaction Failed";
            _logger.LogError($"Error OnPostPostTransactionAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        return Page();
    }
    public async Task<IActionResult> OnPostMmDebitRequestAsync()
    {
        try
        {
            var state = ModelState.IsValid;
            mobileMoneyCreate!.CreatedBy = _userManager.GetUserId(User);
            var apiResp = await _paymentService.UssdPushAsync(mobileMoneyCreate);
            if (apiResp!=null&& apiResp.status!=null &&apiResp.status.response_code!=null && (apiResp.status!.response_code!.ToUpper()== _configuration["IntergrationSettings:ProcessingTransaction"] ||apiResp.status.response_code.ToUpper()== _configuration["IntergrationSettings:SuccessDebitRequest"]))
            {
                TempData["AlertMessage"] = "Mobile Money Initiation Successful";
                return RedirectToPage();
            }
            else
            {
                TempData["ErrorMessage"] = "Mobile Money Initiation Failed";
                ModelState.AddModelError(string.Empty, "Mobile Money Initiation Failed.");
            }
        }
        catch (BadHttpRequestException ex)
        {
            TempData["ErrorMessage"] = "Mobile Money Initiation Failed";
            _logger.LogError($"Error OnPostMmDebitRequestAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        catch (Exception ex)
        {
            TempData["ErrorMessage"] = "Mobile Money Initiation Failed";
            _logger.LogError($"Error OnPostMmDebitRequestAsync: {ex}");
            throw new BadHttpRequestException(ex.Message);
        }
        return RedirectToPage();
    }
}

LetMasterWebApp/Pages/TenantMgt/ListTenantAccounts.cshtml
@page "/TenantAccounts"
@model LetMasterWebApp.Pages.TenantMgt.ListTenantAccountsModel
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Tenant Account List";
}
<h1>Tenant Account List</h1>
<div>
    @if (Model.tenantAccountList != null && Model.tenantAccountList.Items.Count > 0)
    {
        <table class="table table-striped mt-3">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Contact</th>
                    <th>Property Name</th>
                    <th>Unit Number</th>
                    <th>Billing Start Date</th>
                    <th>Agreed Rate</th>
                    <th>Current Balance</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tenantItem in Model.tenantAccountList.Items)
                {
                    var bal = $"<p style=\"color:black;\">{@tenantItem.CurrentBalance.ToString("N2")}</p>";
                    if (tenantItem.CurrentBalance <= 0)
                    {
                        bal = $"<p style=\"color:green;\">{@tenantItem.CurrentBalance.ToString("N2")}</p>";
                    }
                    <tr>
                        <td>@tenantItem.TenantName</td>
                        <td>@tenantItem.TenantMobile</td>
                        <td>@tenantItem.PropertyName</td>
                        <td>@tenantItem.UnitName</td>
                        <td>@tenantItem.StartDate.ToString("MM/dd/yyyy")</td>
                        <td>@tenantItem.AgreedRate.ToString("N2")</td>
                        <td>@Html.Raw(bal)</td>
                        <td><a class="btn btn-sm btn-info manage-btn" asp-page="/TenantMgt/ManageTenantAccount" asp-route-id="@tenantItem.TenantUnitId">Manage</a>
                            <a class="btn btn-sm btn-warning statement-btn" asp-page="/Reports/TenantAccountStatement" asp-route-id="@tenantItem.TenantUnitId">Account Statement</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="mt-3">
            <a href="/tenants?pageIndex=@(Model.tenantAccountList.CurrentPage - 1)&TenantName=@Model.searchModel.TenantName&UnitName=@Model.searchModel.UnitName&PropertyId=@Model.searchModel.PropertyId"
               class="btn btn-primary @(Model.tenantAccountList.HasPrev ? "" : "disabled")">
                Previous
            </a>
            <a href="/tenants?pageIndex=@(Model.tenantAccountList.CurrentPage + 1)&TenantName=@Model.searchModel.TenantName&UnitName=@Model.searchModel.UnitName&PropertyId=@Model.searchModel.PropertyId"
               class="btn btn-primary @(Model.tenantAccountList.HasNext ? "" : "disabled")">
                Next
            </a>
        </div>
    }
    else
    {
        <p class="mt-3">No active tenant accounts found.</p>
    }
</div>
<!--Create Tenant Account Modal -->

LetMasterWebApp/Pages/TenantMgt/ManageTenantAccount.cshtml
@page "/ManageTenantAccount/{id:int}"
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpContext
@model LetMasterWebApp.Pages.TenantMgt.ManageTenantAccountModel
@{
    ViewData["Title"] = "Manage Tenant Account";
}
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["AlertMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<div class="card mb-3">
    <div class="card-header">
        <b>Tenant Account Details</b>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-4">
                <p class="card-text"><b>Tenant</b>: @Model.accountDetails!.TenantName</p>
                <p class="card-text"><b>Contact</b>: @Model.accountDetails.TenantMobile @Model.accountDetails.TenantPhone</p>
                <p class="card-text"><b>Email</b>: @Model.accountDetails.TenantEmail</p>
            </div>
            <div class="col-sm-4">
                <p class="card-text"><b>Property Name</b>: @Model.accountDetails.PropertyName</p>
                <p class="card-text"><b>Location</b>: @Model.accountDetails.PropertyAddress</p>
                <p class="card-text"><b>Owner/Manager</b>: @Model.accountDetails.PropertyManager</p>
                <p class="card-text"><b>Owner/Manager Contact</b>: @Model.accountDetails.PropertyManagerMobile @Model.accountDetails.PropertyManagerPhone</p>
                <p class="card-text"><b>Owner/Manager Email</b>: @Model.accountDetails.PropertyManagerEmail </p>
            </div>
            <div class="col-sm-4">
                <p class="card-text"><b>Unit No.</b>: @Model.accountDetails.UnitNo</p>
                <p class="card-text"><b>Unit Type</b>: @Model.accountDetails.UnitType</p>
                <p class="card-text"><b>Unit Description</b>: @Model.accountDetails.UnitDesc</p>
                <p class="card-text"><b>Agreed Rate</b>: @Model.accountDetails.AgreedRate.Value.ToString("N2")</p>
                <p class="card-text"><b>Start Date</b>: @Model.accountDetails.StartDate</p>
                <p class="card-text"><b>Total Bills</b>: @Model.accountDetails.TotalBills.ToString("N2")</p>
                <p class="card-text"><b>Total Payments</b>: @Model.accountDetails.TotalPayments.ToString("N2")</p>
                <p class="card-text"><b>Current Balance</b>: @Model.accountDetails.CurrentBalance.Value.ToString("N2")</p>
            </div>
        </div>
    </div>
</div>
@if (httpContext.HttpContext!.User.IsInRole("Manager")){
    <div class="mb-3">
        <h4>Tenant Account Management Tools</h4>
        <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#updateTenantAccountModal">
        <strong>Update Account</strong>
    </button>
        <button type="button" class="btn btn-sm btn-outline-warning" data-bs-toggle="modal" data-bs-target="#postTransactionModal">
        <strong>Post Transaction</strong>
    </button>
    </div>
}
@if (httpContext.HttpContext!.User.IsInRole("Tenant"))
{
    <div class="mb-3">
        <button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#mmDebitRequestModal">
            <strong>Pay With Mobile Money</strong>
        </button>
    </div>
}
<br/>
<div class="mb-3">
    <form method="get">
        <div class="d-flex flex-wrap">
            <div class="form-group mr-3">
                <label asp-for="transactionSearch.FromDate"></label>
                <input type="date" class="form-control" id="FromDate" name="FromDate" value="@Model.transactionSearch.FromDate" required>
            </div>
            <div class="form-group mr-3">
                <label asp-for="transactionSearch.ToDate"></label>
                <input type="date" class="form-control" id="ToDate" name="ToDate" value="@Model.transactionSearch.ToDate" required>
            </div>
            <div class="form-group align-self-end">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>
<div class="tab-pane fade show active" id="results" role="tabpanel" aria-labelledby="results-tab">
    @if (Model.transactionList != null && Model.transactionList.Items.Count > 0)
    {
        <h2 class="mt-3">Transaction List</h2>
        <table class="table table-striped mt-3">
            <thead>
                <tr>
                    <th>Transaction Type</th>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>Transaction Date</th>
                    <th>Transaction Mode</th>
                    <th>Transaction Reference</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var txn in Model.transactionList.Items)
                {
                    <tr>
                        <td>
                            @if (txn.TransactionType == "D")
                            {
                                <text>DEBIT</text>
                            }
                            else if (txn.TransactionType == "C")
                            {
                                <text>CREDIT</text>
                            }
                        </td>
                        <td>@txn.Description</td>
                        <td>@txn.Amount!.Value.ToString("N2")</td>
                        <td>@txn.TransactionDate</td>
                        <td>@txn.TransactionMode</td>
                        <td>@txn.TransactionRef</td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="mt-3">
            <a href="/ManageTenantAccount/@Model.accountDetails.Id?pageIndex=@(Model.transactionList.CurrentPage - 1)&FromDate=@Model.transactionSearch.FromDate&ToDate=@Model.transactionSearch.ToDate"
               class="btn btn-primary @(Model.transactionList.HasPrev ? "" : "disabled")">
                Previous
            </a>
            <a href="/ManageTenantAccount/@Model.accountDetails.Id?pageIndex=@(Model.transactionList.CurrentPage + 1)&FromDate=@Model.transactionSearch.FromDate&ToDate=@Model.transactionSearch.ToDate"
               class="btn btn-primary @(Model.transactionList.HasNext ? "" : "disabled")">
                Next
            </a>
        </div>
    }
    else
    {
        <p class="mt-3">No transactions found.</p>
    }
</div>
<!-- Update Tenant Account Modal -->
<div class="modal fade" id="updateTenantAccountModal" tabindex="-1" role="dialog" aria-labelledby="updateTenantAccountModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="updateTenantAccountForm" method="post" asp-page-handler="UpdateTenantAccount">
                @Html.AntiForgeryToken()
                @if (ModelState.IsValid)
                {
                    <div asp-validation-summary="All" class="text-danger"></div>
                }
                <input type="hidden" asp-for="accountUpdate.Id">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateTenantAccountModal">Update Tenant Account</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="accountUpdate.AgreedRate"></label>
                        <input asp-for="accountUpdate.AgreedRate" type="number" class="form-control" required id="unitAmount" />
                    </div>
                    <div class="form-group">
                        <input asp-for="accountUpdate.IsActive" class="form-check-input" id="unitIsActive">
                        <label asp-for="accountUpdate.IsActive" class="form-check-label"></label>
                    </div> 
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Post Transaction Modal [transactionCreate] -->
<div class="modal fade" id="postTransactionModal" tabindex="-1" role="dialog" aria-labelledby="postTransactionModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="postTransactionForm" method="post" asp-page-handler="PostTransaction">
                @Html.AntiForgeryToken()
                @if (ModelState.IsValid)
                {
                    <div asp-validation-summary="All" class="text-danger"></div>
                }
                <input type="hidden" asp-for="transactionCreate.TenantUnitId">
                <div class="modal-header">
                    <h5 class="modal-title" id="postTransactionModalLabel">Post Transaction</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <label asp-for="transactionCreate.TransactionType">*</label>
                    <div class="form-group">
                    <select asp-for="transactionCreate.TransactionType" class="form-control" id="TransactionType">
                        <option value="C">Credit (Add Payment)</option>
                        <option value="D">Debit (AddBill)</option>
                    </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="transactionCreate.Description">*</label>
                        <input asp-for="transactionCreate.Description" required class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="transactionCreate.Amount">*</label>
                        <input asp-for="transactionCreate.Amount" type="number" class="form-control" required id="Amount" />
                    </div>
                    <div class="form-group">
                        <label asp-for="transactionCreate.TransactionMode"></label>
                        <input asp-for="transactionCreate.TransactionMode" placeholder="Cash/Bank/Mobile Money" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="transactionCreate.TransactionRef"></label>
                        <input asp-for="transactionCreate.TransactionRef" class="form-control" placeholder="Receipt no./MM Transaction No." />
                    </div>
                    <div class="form-group">
                        <label asp-for="transactionCreate.TransactionDate">*</label>
                        <input asp-for="transactionCreate.TransactionDate" class="form-control" type="date" required />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!--MM request-->
<div class="modal fade" id="mmDebitRequestModal" tabindex="-1" role="dialog" aria-labelledby="mmDebitRequestModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="mmDebitRequestForm" method="post" asp-page-handler="MmDebitRequest">
                @Html.AntiForgeryToken()
                @if (ModelState.IsValid)
                {
                    <div asp-validation-summary="All" class="text-danger"></div>
                }
                <input type="hidden" asp-for="mobileMoneyCreate.TenantUnitId">
                <div class="modal-header">
                    <h5 class="modal-title" id="mobileMoneyCreateModalLabel">Pay With Mobile Money</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="mobileMoneyCreate.Amount"></label>
                        <input asp-for="mobileMoneyCreate.Amount" type="number" class="form-control" required id="Amount" placeholder="500 - 5,000,000"/>
                    </div>
                    <div class="form-group">
                        <label asp-for="mobileMoneyCreate.DebitNumber"></label>
                        <input asp-for="mobileMoneyCreate.DebitNumber" class="form-control" placeholder="eg .752123456"/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Initiate Mobile Money Payment</button>
                </div>
            </form>
        </div>
    </div>
</div>